const state={time:'21:10',clues:[],questions:[],selectedClues:[],selectedSuspect:null,trust:42,interviewed:false};
const evidence=[{id:'receipt',label:'Hóa đơn bị xé',desc:'Quán Thanh Xuân — 22:17',detail:'Một hóa đơn cà phê bị xé đôi. Mực in vẫn còn mới.'},{id:'radio',label:'Radio cũ',desc:'Kênh FM 91.5 — 23:17',detail:'Chương trình đêm được hẹn giờ phát lại lúc 23:17, sau thời điểm tử vong.'},{id:'window',label:'Cửa sổ',desc:'Khóa từ bên trong',detail:'Chốt cửa vẫn cài. Bên ngoài là hẻm cụt, không có dấu chân.'},{id:'shoe',label:'Vết giày',desc:'Cỡ 41 — cạnh bàn',detail:'Kích thước không khớp với nạn nhân. Đế giày có một hình tam giác nhỏ.'},{id:'phone',label:'Điện thoại',desc:'Cuộc gọi đi — 22:31',detail:'Cuộc gọi kéo dài 13 giây. Số nhận đã bị xóa khỏi danh bạ.'},{id:'number',label:'Con số trên tường',desc:'13 / mực đỏ',detail:'Nét viết bị che dưới lớp sơn. Ai đó đã cố xóa nó.'}];
const known=[['phone','Điện thoại nạn nhân gọi lúc 22:31',true],['window','Cửa bị khóa từ bên trong',true],['shoe','Vết giày không khớp với nạn nhân',false],['radio','Radio được hẹn phát lúc 23:17',false],['number','Con số 13 dưới lớp sơn',false]];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function renderActions(){const el=$('#explore-actions');el.innerHTML=evidence.map(item=>`<button class="action-button" data-evidence="${item.id}"><span>${state.clues.includes(item.id)?'✓ ĐÃ GHI':'◌ TƯƠNG TÁC'}</span>${item.label}<small>${item.desc}</small></button>`).join('');$$('.action-button').forEach(b=>b.onclick=()=>inspect(b.dataset.evidence));}
function inspect(id){if(!state.clues.includes(id)){state.clues.push(id);const item=evidence.find(x=>x.id===id);state.questions.push(item.detail);renderNotebook();renderActions();$('#clue-count').textContent=state.clues.length;}const item=evidence.find(x=>x.id===id);$('#hypothesis').textContent=item.detail;}
function renderNotebook(){const el=$('#known-list');el.innerHTML=known.map(([id,text,done])=>`<div class="known-item ${state.clues.includes(id)||done?'':'pending'}"><span class="check">${state.clues.includes(id)||done?'☑':'☐'}</span><span>${text}</span></div>`).join('');}
function showPanel(name){$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.panel===name));$$('.panel-body').forEach(p=>p.classList.add('hidden'));$(`#${name}-panel`).classList.remove('hidden');const titles={explore:'Căn phòng 204',interview:'Phòng trực bảo vệ',deduce:'Bảng suy luận',conclude:'Bản kết luận'};$('#panel-title').textContent=titles[name];}
function renderInterview(){const actions=[['TIN','Tin lời khai của ông ta.'],['NGHI NGỜ','Hỏi về camera mất tín hiệu.'],['ĐƯA BẰNG CHỨNG','Đưa hóa đơn lúc 22:17.']];$('#interview-actions').innerHTML=actions.map(([title,text],i)=>`<button class="dialogue-option" data-choice="${i}"><b>[ ${title} ]</b>${text}</button>`).join('');$$('.dialogue-option').forEach(b=>b.onclick=()=>talk(+b.dataset.choice));}
function talk(choice){state.interviewed=true;let line='',result='';if(choice===0){line='"Cuối cùng cũng có người chịu tin tôi. Nhưng đêm đó... tôi nghe tiếng radio từ tầng hai."';state.trust+=7;result='Bảo kể thêm về tiếng radio. Ông ta vẫn giấu điều gì đó.'}if(choice===1){line='"Camera mất tín hiệu có vài phút thôi. Tôi đã báo lên trên rồi."';state.trust-=4;result='Ông ta né câu hỏi về việc đã rời phòng trực.'}if(choice===2){line='"Tôi... chỉ ra ngoài mua thuốc. 22:17. Chuyện đó có gì quan trọng?"';state.trust-=9;result='Lời khai thay đổi. Ông ta đã nói dối, nhưng lý do có thể không liên quan đến án mạng.'}$('#guard-line').textContent=line;$('#trust-fill').style.width=`${state.trust}%`;$('#trust-value').textContent=`${state.trust}%`;$('#interview-result').textContent=result;$('#interview-result').classList.remove('hidden');}
function renderBoard(){const cards=evidence.filter(x=>state.clues.includes(x.id));$('#board').innerHTML=cards.length?cards.map(c=>`<button class="clue-card" data-id="${c.id}"><strong>${c.label}</strong><p>${c.desc}</p></button>`).join(''):'<div class="result-box">Bạn chưa ghi đủ dữ kiện. Hãy quay lại hiện trường.</div>';$$('.clue-card').forEach(b=>b.onclick=()=>selectClue(b.dataset.id));}
function selectClue(id){if(state.selectedClues.includes(id))state.selectedClues=state.selectedClues.filter(x=>x!==id);else if(state.selectedClues.length<2)state.selectedClues.push(id);$$('.clue-card').forEach(b=>b.classList.toggle('selected',state.selectedClues.includes(b.dataset.id)));if(state.selectedClues.length===2){const pair=state.selectedClues.sort().join('-');const insight=pair==='number-phone'?'Số 13 xuất hiện trong cuộc gọi bị xóa. Ai đó đã biết cuộc điều tra sẽ bắt đầu.':pair==='radio-shoe'?'Vết giày và chương trình radio cùng trỏ về một người đã có mặt sau thời điểm tử vong.':'Hai dữ kiện này chưa đủ để kết luận, nhưng chúng đặt ra một câu hỏi mới.';$('#hypothesis').textContent='🔗 GIẢ THUYẾT: '+insight;}}
function renderSuspects(){const suspects=[['Bảo vệ Trần Văn Bảo','Đã nói dối về việc rời phòng trực'],['Người phụ nữ tầng 3','Không có tên trong sổ khách'],['Nguyễn Minh','Nạn nhân — cái chết có thể đã được dàn dựng'],['Người gọi lúc 22:31','Danh tính bị xóa khỏi điện thoại']];$('#suspect-options').innerHTML=suspects.map((x,i)=>`<button class="suspect" data-suspect="${i}">${x[0]}<small>${x[1]}</small></button>`).join('');$$('.suspect').forEach(b=>b.onclick=()=>{$$('.suspect').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selectedSuspect=+b.dataset.suspect;});}
function conclude(){if(state.selectedSuspect===null){$('#conclusion-result').textContent='Chọn một giả thuyết trước khi đóng hồ sơ.';$('#conclusion-result').classList.remove('hidden');return}const good=state.selectedSuspect===3;$('#conclusion-result').textContent=good?'Hồ sơ tạm thời ghi nhận: người gọi lúc 22:31 là đầu mối trực tiếp. Nhưng cái tên phía sau số điện thoại vẫn còn trống.':'Hồ sơ tạm thời ghi nhận nghi phạm này. Thành phố sẽ tiếp tục dựa trên kết luận của bạn — kể cả khi nó sai.';$('#conclusion-result').classList.remove('hidden');}
$$('.tab').forEach(t=>t.onclick=()=>{const p=t.dataset.panel;showPanel(p);if(p==='interview')renderInterview();if(p==='deduce')renderBoard();if(p==='conclude')renderSuspects();});$('#clear-links').onclick=()=>{state.selectedClues=[];renderBoard();$('#hypothesis').textContent='Chọn hai dữ kiện để thử tạo một giả thuyết.'};$('#save-question').onclick=()=>{const input=$('#question');if(input.value.trim()){state.questions.push(input.value.trim());input.value='';$('#hypothesis').textContent='Câu hỏi đã được ghi lại. Không ai nhắc bạn phải hỏi câu này.'}};$('#submit-conclusion').onclick=conclude;renderActions();renderNotebook();